pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/SawanPanwar/django-docker-jenkins.git', branch: 'main'
            }
        }

        stage('Deploy Using Docker Compose') {
            steps {
                script {
                    dir('SOS') {
                        bat 'docker-compose down || docker-compose.exe down'
                        bat 'docker-compose up -d --build || docker-compose.exe up -d --build'
                    }
                }
            }
        }
    }
}