pipeline {
    agent any 

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/jalaj8009/django-jenkins-docker.git', branch: 'main'
            }
        }
        
        stage('Setup') {
            steps {
                bat 'python -m venv venv' // Create a virtual environment
            }
        }
        
        stage('Install Dependencies') {
            steps {
                bat 'call venv\\Scripts\\activate.bat'
                bat 'pip install -r SOS\\requirements.txt'
            }
        }
        
        stage('Run Application') {
            steps {
                bat 'call venv\\Scripts\\activate.bat'
                dir('SOS') {
                    bat 'start /B python manage.py runserver 0.0.0.0:8080' // Run the app in background
                }
                script {
                    // Print the link to the console
                    echo 'Django application running at: http://localhost:8080'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            bat 'call venv\\Scripts\\deactivate.bat' // Deactivate the virtual environment
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
